### PR TITLE
Add an Actions workflow which tests byte compilation

### PR DESCRIPTION
**Pull request by purcell**
Here's a minimal CI example.

### CODE REVIEW

**Comment by purcell** [comment]
Untested, and I don't know if Actions will start running in your repo as a result of me randomly sending you a PR (look in the repo settings if not), but this should at least help point you in the right direction.

**Comment by purcell** [comment]
You can see it doing stuff in the fork I created: https://github.com/purcell/hermeneus/runs/2019933853?check_suite_focus=true

It's failing on byte-compilation issues, as expected.

If you merge the PR, Actions should start running here too, initially with the same result.

**Comment by TinaRussell** [comment]
Wow, thanks! I’m curious how I should specify external dependencies, like the “anaphora” package from MELPA (the absence of which is generating an error in the test).

**Comment by purcell** [comment]
There's Cask for that, but I feel like it's falling a little out of maintenance. Here's an example of a simple Makefile with commands that will pre-install certain commands for you: https://github.com/purcell/exec-path-from-shell/blob/master/Makefile

You might eventually find it instructive to write `hermeneus` as a well-formed package, in which case [package-lint](https://github.com/purcell/package-lint) will help you out: the Makefile above shows its simple usage. Multi-file packages are a little different, but you get the general idea.

**Comment by purcell** [comment]
Also it's easy to have a "build status" badge in your main README, but I was too lazy to look up the Org syntax for linked images. See the README.md in the above repo for a Markdown example though.

**Comment by akirak** [comment]
@TinaRussell Congratulations! For status badges in your Org README, I'd recommended embedding HTML. Here is an example: https://raw.githubusercontent.com/alphapapa/org-ql/master/README.org

**Comment by purcell** [comment]
The setup-cask action - together with a Cask file - would probably be a convenient way to specify external dependencies btw: https://github.com/conao3/setup-cask

**Comment by TinaRussell** [comment]
@purcell So, if I understand this correctly: if I want to use setup-cask, I need to adapt `.github/workflows/ci.yml` to include the stuff shown in the setup-cask config examples (in particular, the “matrix testing” example), and then write a Cask configuration file that specifies the dependency? If so, I’m still a bit confused… for instance, the setup-cask yml example has `- uses: actions/checkout@v1` towards the beginning of the “steps” part, while the `ci.yml` that you wrote has `- uses: actions/checkout@v2` towards the end. What does that part do, and does the order matter? Will I need to write a Makefile, or can I simply enter a relevant command with “run:” the way you did? …Anything else I should know? Thanks for all your help :relaxed:

**Comment by purcell** [comment]
I haven't used `setup-cask` myself, but yes, that's the basic scheme.

You need the `checkout` action to happen before you refer to any files in the repo! :-)

No Makefile will be necessary, but you presumably need to run a cask-based command to make the magic happen.

**Comment by TinaRussell** [comment]
So, I added setup-cask to `ci.yml`, made a short Cask file with the dependency, added a command to `ci.yml` to install dependencies, and (of course) my build is still failing. https://github.com/TinaRussell/hermeneus/runs/2070949614 I get the usual byte-compiler warnings, but also a lot of errors saying that functions which should be defined already at that point somehow aren’t (any insight would be appreciated :sweat_smile:). But, what really blows my mind are the errors that say that `anaphora`, the one dependency, cannot be found! :sob: I can see in the logs that Cask said it installed it, and yet the build’s Emacs can’t find it. Any idea what is going on? :dizzy_face: I really appreciate your patience with this.
(Edit: I thought the problem might be that the call to `emacs` in `ci.yml` includes `-Q` and `-batch` but no instruction to call `(package-initialize)` (since even Emacs 27 won’t load packages automatically when in batch mode), so I added one, but it still doesn’t work. You can see what ci.yml looks like now, here: [https://github.com/TinaRussell/hermeneus/blob/master/.github/workflows/ci.yml](https://github.com/TinaRussell/hermeneus/blob/master/.github/workflows/ci.yml))

**Comment by purcell** [comment]
IIRC you have to run `cask emacs` instead of just emacs.

**Comment by TinaRussell** [comment]
Following from what you said, I replaced the Emacs command with `cask build` and it works now! Hooray!

**Comment by purcell** [comment]
Nice!

**Pull request merged**
